import Head from "next/head";
import { getAllPosts, getAllTags } from "../lib/api/posts";
import PostType from "../lib/models/post";
import styles from "../styles/Home.module.css";

import MainPage from "../components/mainpage";
import React, { ReactElement } from "react";
import Layout from "../components/layout/layout";
import { LayoutSidebar } from "../components/layout/sidebar";
import { slide as Menu } from "react-burger-menu";
import { Tagcloud } from "../components/widgets/tagcloud";

type Props = {
  allPosts: PostType[];
  tags: string[];
};

const Index = ({ allPosts, tags }: Props) => {
  console.log(allPosts);

  return (
    <div>
      
      {/* <div id="outer-container" style={{ height: '100%' }}>
      </div> */}
      {/* <Menu  pageWrapId={ "page-wrap" } outerContainerId={ "outer-container" }>
        <a id="about" className="menu-item" href="/about">
          About
        </a>
        <a id="contact" className="menu-item" href="/contact">
          Contact
        </a>
        <main id="page-wrap">
          <div>
            <h3>tags</h3>
              <Tagcloud tags={tags} />
          </div>
          
      </main>
    
      </Menu> */}

<div className={styles.container}>

<Head>
          <title>next static blog</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <MainPage allPosts={allPosts} />
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
          
        </footer>

</div>
      
      </div>
      
  );
};

Index.getLayout = function getLayout(page: ReactElement) {
  console.log(page)
  let tags = page.props.tags;
  return (
    <Layout>
      <LayoutSidebar tags={tags} />
      {page}
    </Layout>
  );
};

export default Index;

export const getStaticProps = async () => {
  // const allPosts = getAllPosts([
  //   'title',
  //   'date',
  //   'slug',
  //   'author',
  //   'coverImage',
  //   'excerpt',
  // ])
  let post1 = {
    slug: "string",
    title: "string",
    date: "st",
    coverImage: "string",
    author: "string",
    excerpt: "string",
    ogImage: {
      url: "string",
    },
    content: "string",
  };
  let allPostsList = [post1, post1];
  let allPosts: any = null;
  allPosts = getAllPosts(["title", "date", "slug", "coverImage", "excerpt"]);
  console.log(allPosts);
  const tags = getAllTags();
  return {
    props: { allPosts, tags },
  };
};
