import Head from 'next/head'
import { getAllPosts } from '../lib/api/posts'
import PostType from '../lib/models/post'
import styles from '../styles/Home.module.css'

import MainPage from '../components/mainpage'



type Props = {
  allPosts: PostType[]
}

const Index = ({ allPosts }: Props) => {
  console.log(allPosts)

  return (
    <div className={styles.container}>
      <MainPage allPosts={allPosts}/>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>

    
  )
}

export default Index;

export const getStaticProps = async () => {
  // const allPosts = getAllPosts([
  //   'title',
  //   'date',
  //   'slug',
  //   'author',
  //   'coverImage',
  //   'excerpt',
  // ])
  let post1 = {
    slug: 'string',
    title: 'string',
    date: 'st',
    coverImage: 'string',
    author: 'string',
    excerpt: 'string',
    ogImage: {
      url: 'string',
    },
    content: 'string',
  }
  let allPostsList = [post1, post1]
  let allPosts: any = null;
  allPosts = getAllPosts([
    'title',
    'date',
    'slug',
    'coverImage',
    'excerpt',
  ])
  console.log(allPosts)
  return {
    props: { allPosts },
  }
}

