import Head from 'next/head'
import { useRouter } from 'next/router'
import React from 'react'
import MainPage from '../../components/mainpage'
import { getAllPosts, getAllPostsByTag, getAllTags } from '../../lib/api/posts'
import PostType from '../../lib/models/post'
import styles from '../../styles/Home.module.css'





type Props = {
  allPostsByTag: PostType[]
}

const Tags = ({ allPostsByTag }: Props) => {
  console.log("18:", allPostsByTag)
  return (
    <div className={styles.container}>
      <MainPage allPosts={allPostsByTag}/>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        
      </main>

      
    </div>

    
  )
}

export default Tags;

type Params = {
  params: {
    tag: string,
  }
}

export const getStaticProps = async ({params}: Params) => {
  let allPostsByTag: any = null;
  allPostsByTag = getAllPostsByTag(params.tag, [
    'title',
    'date',
    'slug',
    'coverImage',
    'excerpt',
  ])
  console.log(allPostsByTag)
  return {
    props: { allPostsByTag },
  }
}

export async function getStaticPaths() {
  const tags = getAllTags()
  return {
    paths: tags.map((tag: string) => {
      return {
        params: {
          tag: tag
        },
      }
    }),
    fallback: false,
  }
}
